version: "3.7"
services:
  infra:
    build:
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /infra/env/$ENVIRONMENT
    user: root
    entrypoint: ""
    volumes:
      - $HOME:/root/:rwo
      - $HOME/.cache/terraform-providers:/.tfcache
      - $HOME/.cache/helm:/root/.cache/helm
      - $HOME/.config/helm:/root/.config/helm
      - $HOME/.aws/cli/cache:/root/.aws/cli/cache
      - ./:/infra
    environment:
      - TF_PLUGIN_CACHE_DIR=/.tfcache
      - TF_VAR_project_name=$PROJECT_NAME
      - TF_LOG
      - AWS_PROFILE
      - AWS_STS_REGIONAL_ENDPOINTS=regional
      - AWS_SDK_LOAD_CONFIG=1
